operator:
  pullPolicy: IfNotPresent
  replicas: 1
  image: tomekincubly/kafka-schema-operator
  version: latest
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

schemaRegistry:
#  base URL of the "default" schema registry instance. Overridable on resource level
  baseUrl:

# global cleanup policy for the operator, Overridable on resource level
defaultCleanupPolicy: DISABLED

# global schema normalize option. Currently work only for AVRO. Overridable on resource level
defaultNormalize: false

# reconciliation loop requeue delay. Defaults to 1m (60s).
# Format: a possibly signed sequence of decimal numbers,
# each with optional fraction and a unit suffix,
# such as "300ms", "-1.5h" or "2h45m".
# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
#
# Negative value - don't requeue (disable reconciliation loop)
# Zero - requeue with exponential backoff
requeueDelay: 1m

deploymentLabels: {}
deploymentAnnotations: {}
podLabels: {}
podAnnotations: {}
